line-length = 88
target-version = "py311"
src = ["src", "tests"]

[lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
  "UP", # pyupgrade
  "N",  # pep8-naming
  "D",  # pydocstyle
  "ANN" # annotations
]
ignore = [
  "D100", "D104", "D105", "D107",  # module/class/magic docstrings optional
  "ANN101", "ANN102",                 # no type for self/cls
  "ANN401"                             # allow Any in some places
]

[lint.isort]
combine-as-imports = true
force-single-line = false
